import { User, Book, Feather, AlertCircle, Copy, Share2 } from 'lucide-react';

export function AnswerCard() {
  return (
    <div className="bg-white rounded-3xl shadow-medium border border-stone-100 overflow-hidden">

      {/* Question Header */}
      <div className="bg-stone-50/50 border-b border-stone-100 p-8 md:p-10">
        <div className="flex items-center gap-2 mb-4">
          <div className="h-6 w-6 rounded-full bg-amber-100 flex items-center justify-center text-amber-700">
            <User className="w-3.5 h-3.5" />
          </div>
          <span className="text-xs font-semibold text-stone-400 uppercase tracking-wider">Your Inquiry</span>
        </div>
        <h2 className="font-serif text-2xl md:text-3xl leading-snug text-stone-900">
          Why did Rama choose to exile Sita specifically to Valmiki&apos;s ashram?
        </h2>
      </div>

      <div className="p-8 md:p-10 space-y-10">

        {/* Main Answer */}
        <div className="prose prose-stone prose-lg max-w-none">
          <p className="font-serif text-lg leading-loose text-stone-700">
            <span className="text-4xl float-left mr-2 mt-[-10px] text-amber-500 font-serif">R</span>ama did not explicitly strategically choose Valmiki&apos;s ashram. The texts describe that Lakshmana, under Rama&apos;s orders, took Sita to the banks of the Ganges near the Tamasa river. It was a location coincidentally close to the hermitage.
          </p>
          <p className="font-serif text-lg leading-loose text-stone-700">
            Upon being abandoned, Sita was found weeping by the sage&apos;s disciples. Recognizing her distress and divine nature, Valmiki offered her sanctuary, citing his knowledge of her purity and his past friendship with King Dasharatha.
          </p>
        </div>

        {/* Source Card */}
        <div className="bg-stone-900 rounded-2xl p-6 text-stone-200 shadow-xl relative overflow-hidden group">
          {/* Decorative gradient blob */}
          <div className="absolute top-0 right-0 w-32 h-32 bg-amber-500/20 blur-3xl rounded-full group-hover:bg-amber-500/30 transition-all duration-700"></div>

          <div className="relative z-10">
            <div className="flex items-center justify-between mb-4 border-b border-white/10 pb-4">
              <span className="text-xs font-medium text-amber-500 uppercase tracking-widest">Source Text</span>
              <span className="text-xs font-mono text-stone-400">Uttara Kanda 49.10–18</span>
            </div>
            <blockquote className="font-serif italic text-lg leading-relaxed text-stone-100 mb-4 opacity-90">
              &ldquo;The sage Valmiki, hearing the sound of weeping, approached the grief-stricken Vaidehi and offered her protection within his hermitage.&rdquo;
            </blockquote>
            <div className="flex items-center gap-2 text-xs text-stone-500">
              <Book className="w-3 h-3" />
              <span>Critical Edition, Baroda</span>
            </div>
          </div>
        </div>

        {/* Insights Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="p-5 rounded-2xl border border-stone-100 bg-stone-50/50">
            <h4 className="text-xs font-semibold text-stone-900 uppercase tracking-wide mb-2 flex items-center gap-2">
              <Feather className="w-3 h-3 text-amber-600" /> Narrative Role
            </h4>
            <p className="text-sm text-stone-600 leading-relaxed">
              Valmiki&apos;s intervention bridges the event and the epic&apos;s composition, as he later teaches the poem to Lava and Kusha there.
            </p>
          </div>
          <div className="p-5 rounded-2xl border border-stone-100 bg-stone-50/50">
            <h4 className="text-xs font-semibold text-stone-900 uppercase tracking-wide mb-2 flex items-center gap-2">
              <AlertCircle className="w-3 h-3 text-amber-600" /> Interpretive Note
            </h4>
            <p className="text-sm text-stone-600 leading-relaxed">
              Unlike later retellings, the Valmiki Ramayana presents the abandonment as a severing of ties, with Valmiki&apos;s aid being an independent act.
            </p>
          </div>
        </div>

      </div>

      {/* Footer */}
      <div className="bg-stone-50 px-8 py-4 border-t border-stone-100 flex justify-between items-center">
        <span className="text-xs text-stone-400 font-medium">Generated by Tattva v1.0</span>
        <div className="flex gap-3">
          <button className="p-2 rounded-lg hover:bg-white hover:shadow-sm text-stone-400 hover:text-stone-900 transition-all">
            <Copy className="w-4 h-4" />
          </button>
          <button className="p-2 rounded-lg hover:bg-white hover:shadow-sm text-stone-400 hover:text-stone-900 transition-all">
            <Share2 className="w-4 h-4" />
          </button>
        </div>
      </div>
    </div>
  );
}
